SELECT 'YOUNGEST' as TYPE, NAME, BIRTHDATE as BIRTHDAY
FROM WORKER
WHERE BIRTHDATE IN (
    SELECT BIRTHDATE
    FROM WORKER
    ORDER BY BIRTHDATE DESC
    LIMIT 1
)

UNION

SELECT 'OLDEST' as TYPE, NAME, BIRTHDATE as BIRTHDAY
FROM WORKER
WHERE BIRTHDATE IN (
    SELECT BIRTHDATE
    FROM WORKER
    ORDER BY BIRTHDATE
    LIMIT 1
)
;

