SELECT c.NAME, COUNT(p.CLIENT_ID) as PROJECT_COUNT
FROM CLIENT c
         JOIN PROJECT p on c.ID = p.CLIENT_ID
GROUP BY c.NAME
HAVING COUNT(p.CLIENT_ID) IN (
    SELECT COUNT(CLIENT_ID)
    FROM PROJECT p2
    GROUP BY p2.CLIENT_ID
    ORDER BY COUNT(CLIENT_ID) DESC
    LIMIT 1
    );

