SELECT P.NAME, DATEDIFF(MONTH, P.START_DATE, P.FINISH_DATE) * SUM(W.SALARY) PRICE
FROM PROJECT P
         JOIN PROJECT_WORKER PW on P.ID = PW.PROJECT_ID
         JOIN WORKER W on W.ID = PW.WORKER_ID
GROUP BY P.NAME
ORDER BY PRICE DESC;
